### ISSUE TITLE
Bounties

### ISSUE THREAD

**Issue by cagatayldzz** [WFCD/warframe-worldstate-parser#131]
### Genesis Issue
---

**Summary (short):**
x2 it seems
Solaris United and Ostrons

---
**Description:**
the problem comes up when the time expires
time estimate(eta): +12:30 minutes

---
**If issue, Reproduction:**

---
**Evidence:**
![123](https://user-images.githubusercontent.com/7725575/49309975-0d758700-f4ee-11e8-907b-dc4b8205106d.PNG)

**Comment by TobiTenno** [comment]
should be fixed with v2.1.25. lemme know if it's still breaking for ya.

**Comment by cagatayldzz** [comment]
The problem persists
