### ISSUE TITLE
streamlined form

### ISSUE THREAD

**Issue by cagatayldzz** [WFCD/warframe-worldstate-parser#133]
### Genesis Issue
---

**Summary (short):**
value undefined

---
**Description:**
no problem but there is something wrong 😅
> https://github.com/WFCD/warframe-worldstate-data/blob/master/data/languages.json#L8454-L8456

---
**Evidence:**
![image](https://user-images.githubusercontent.com/7725575/49855761-3277cd00-fdff-11e8-83a1-bda920e78fbd.png)
![23](https://user-images.githubusercontent.com/7725575/49856502-ff363d80-fe00-11e8-86ea-771f84fa451f.PNG)

**Comment by TobiTenno** [comment]
hadn't released the new `data` changes yet, it's released and pushed now.
