### ISSUE TITLE
flashSales

### ISSUE THREAD

**Issue by cagatayldzz** [WFCD/warframe-worldstate-parser#134]
### Genesis Feature Request
---

**Description:**
Can you add "RegularOverride" to show credit

---
Warframe worldState (sample picture)
![image](https://user-images.githubusercontent.com/7725575/50372570-cf95eb00-05e1-11e9-886c-78e16657b60f.png)

**Comment by TobiTenno** [comment]
> Genesis Feature Request
> warframe-worldstate-parser

there is more than a few layers to this, please separate your requests. feel free to implement yourself, also, all of the above are open source so that when i can't do them all the time, people are welcome to submit PRs.

**Comment by TobiTenno** [comment]
added in [`60611b`](https://github.com/WFCD/warframe-worldstate-parser/commit/60611bab9bb199f025b519d2f8d8bb979f4e1a69)
