### ISSUE TITLE
globalUpgrades

### ISSUE THREAD

**Issue by cagatayldzz** [WFCD/warframe-worldstate-parser#135]
### Genesis Feature Request
---

**Summary (short):**
Can you add special event data

![image](https://user-images.githubusercontent.com/7725575/50376399-6b911800-061d-11e9-9edc-500d9a386121.png)

---
can be shown in events
![image](https://user-images.githubusercontent.com/7725575/50376427-c3c81a00-061d-11e9-9f44-537b8022f1f4.png)

**Comment by TobiTenno** [comment]
"special event" data is already shown in events when it's present, but global upgrades is a different data set with a different purpose.

**Comment by TobiTenno** [comment]
The problem is that "GlobalUpgrades" are a totally different can of worms, and making them into something they're not makes our data inaccurate and most likely duplicated
