### ISSUE TITLE
incorrect nomenclature

### ISSUE THREAD

**Issue by cagatayldzz** [WFCD/warframe-worldstate-parser#137]
### Genesis Issue
---

**Summary (short):**

❌ | ✔️
------------ | -------------
Tenno Ii | Tenno II

---
**Evidence:**
![image](https://user-images.githubusercontent.com/7725575/51751904-18503080-20c7-11e9-847f-19c2365009af.png)

**Comment by TobiTenno** [comment]
that's the automated translation and formatting, not an issue. It's not going to be able to automatically pick up roman numerals.

**Comment by TobiTenno** [comment]
I'm not finding that string anywhere in our language files

**Comment by cagatayldzz** [comment]
> languages.json
![image](https://user-images.githubusercontent.com/7725575/51759654-c9f85d00-20d9-11e9-8ba8-ad58b27fbc76.png)

**Comment by TobiTenno** [comment]
that's not here
