### ISSUE TITLE
Q: Arbritations and Kuva Siphons

### ISSUE THREAD

**Issue by cswl** [WFCD/warframe-worldstate-parser#154]
Just wondering do we not have current Arbritations  and Kuva Siphons in world state.

With the new changes to Arbritations more people wanna keep an check on current Arbritation for Excavation, Interception.
Although, the buffs are different for each user.. the node/mission is the same for everyone

What about Kuva Siphons.. manually searching for Kuva flood every few hours can be daunting too.

**Comment by TobiTenno** [comment]
They're not parsed because they're not in the worldstate that DE provides.

**Comment by cswl** [comment]
So the only way to get Arbritations updates would be to use Nexus bot like OCR scanning . Huh :/,

**Comment by TobiTenno** [comment]
or something similar, yeah. there's a discord server where they have users post a screenshot of the current arbitration and the bot processes it and pings, but that's not something that really scales well.
