### ISSUE TITLE
Time wrong and unstable interface

### ISSUE THREAD

**Issue by Richasy** [WFCD/warframe-worldstate-parser#167]
### Genesis Issue
---

**Summary (short):**  
Some data in the interface, such as vallis, fissure, etc., there is a problem with expiry time, one to two hours behind normal time.  
At the same time, Kuva and Arbitration often have no data.  

---
**Description:**  
I am very grateful to the author for his hard work.  
Some data in the interface, such as vallis, fissure, etc., there is a problem with expiry time, one to two hours behind normal time.  
At the same time, Kuva and Arbitration often have no data.  

---
**Evidence:**  
This is the data from the [hub](https://hub.warframestat.us/#/), but for the same reason.  
![c553b8e1-a102-4f47-a75e-e19b23477886.png](https://storage.live.com/items/51816931BAB0F7A8!13442?authkey=AO7QXpgYo7-5DUU)

**Comment by TobiTenno** [comment]
Have you checked your computer's time settings?

**Comment by TobiTenno** [comment]
And kuva and arbitration are purposely not in the [swagger doc](https://docs.warframestat.us) for that exact reason.

**Comment by TobiTenno** [comment]
The data on the interface is always built and transmitted as either a utc timestamp string or an epoch millisecond timestamp

**Comment by Richasy** [comment]
Yes, after I had this problem, I checked my time zone settings for the first time and found that there was no problem. Then I checked the data provided by the interface and found that there was a lag in time. In UTC time, no matter what, the expiration time of the task should be greater than the current time, but in terms of the data obtained by the interface, this is not the case.

**Comment by TobiTenno** [comment]
This seems to be the case only for you, however, because it's working perfectly fine day to day for the rest of us

**Comment by TobiTenno** [comment]
Or, if it's something intermittent at present, not a chronic issue, you need to state that, because how you're detailing it makes it sound like it it's a constant issue.

**Comment by Richasy** [comment]
Ok, this is indeed a problem that I have encountered, and it is also very important. After all, the most important thing is time. But can you try to visit the [hub](https://hub.warframestat.us/#/)? I hope to get the results from your side, which helps me to determine the cause of the problem. Thank you

**Comment by Richasy** [comment]
Today the problem has been solved, it seems that it is suddenly normal, thanks to the help of developers
