### ISSUE TITLE
Use mobile api endpoint solnodes for translations

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-worldstate-parser#185]
**Summary (short):**
Apparently the mobile api has an endpoint for sol nodes?

---
**Description:**
No clue

---
**Mockups:**

**Comment by Kaptard** [comment]
To get localized solar node strings:
1) Request `http://content.warframe.com/PublicExport/index_<lang_tag>.txt.lzma`  where `lang_tag` can be `["en", "de", "fr", "it", "ko", "es", "zh", "ru", "ja", "pl", "pt", "tc", "tr", "uk"]`
2) Decompress the file and look for the string that starts with `ExportRegions_<lang_tag>.json`
3) Get the list of localized solar nodes from `http://content.warframe.com/PublicExport/Manifest/ExportRegions_<lang_tag>.json!<hash_from_step_2>`

This process is fairly analogous to [how we fetch things for warframe-items](https://github.com/WFCD/warframe-items/blob/development/build/scraper.js).

**Comment by TobiTenno** [comment]
sounds like it's time to add an autoupdate for worldstate data again...

**Comment by TobiTenno** [comment]
i think i got the issues we were having sorted... i may do this in the long run, but it's not super pressing
