### ISSUE TITLE
Arbitration's parse is abnormal

### ISSUE THREAD

**Issue by Richasy** [WFCD/warframe-worldstate-parser#196]
**Summary (short):**

In the parsed json data, the time and task of the arbitration have some exceptions, which may be an error in the data source or the parsing process

---

**Description:**

*Api Data:*

```json
{
    "activation": "2020-04-07T23:05:00Z",
    "expiry": "2020-04-09T00:04:00Z",
    "enemy": "Corpus",
    "type": "Interception",
    "archwing": false,
    "sharkwing": false,
    "node": "Cerberus (Pluto)"
}
```

*Actual Data:*

type is **Defense**, node is **Lua (STöFLER)**, 40 minutes left.

**Comment by TobiTenno** [comment]
we receive the data from https://10o.io/kuvalog.json and select the arbitration that encompasses the current time. i'll see if there's anything going on with their site, but that's about as far as I can get in diagnosing it.

**Comment by TobiTenno** [comment]
Looks like the types on them are all the same now.

**Comment by Richasy** [comment]
It seems that we only need to fetch the first data in the array, the other data are historical messages and do not need to be processed.

Just need this:

```json
{
    "start": "2020-04-08T07:00:00.000Z",
    "end": "2020-04-08T08:05:00.000Z",
    "missiontype": "EliteAlertMission",
    "solnode": "ClanNode3",
    "solnodedata": {
      "name": "Tikal [EARTH]",
      "tile": "Tikal",
      "planet": "Earth",
      "enemy": "Infested",
      "type": "Excavation",
      "node_type": "NT_CLAN",
      "archwing": false,
      "sharkwing": false
    },
    "realtime": "2020-04-08T07:00:19.607Z"
  }
```

**Comment by TobiTenno** [comment]
except that, due to the nature of arrays as a data structure, I can't be reliably sure it's always the first one.
