### ISSUE TITLE
Use HTTPS worldstate instead of HTTP

### ISSUE THREAD

**Issue by NKN1396** [WFCD/warframe-worldstate-parser#230]
**Summary (short):**
This repo is still using the HTTP address of Warframe worldstate. This is unsafe by modern standards.
---
**Description:**
Files like readme.md still refer to using the non-secure link (`http://content.warframe.com/dynamic/worldState.php`). Worldstate can be acquired securely from `https://content.warframe.com/dynamic/worldState.php` instead.

**Comment by TobiTenno** [comment]
You can use whichever you want. It doesn't matter for demonstration purposes, which is what the readme is for
