### ISSUE TITLE
Swapped Deimos bounty rewards

### ISSUE THREAD

**Issue by lumpman2** [WFCD/warframe-worldstate-parser#242]
Summary (short):
Deimos bounty level 2 and 3 (endless) rewards reversed

Description:
Not sure if this is a error with the data itself or just on the display, but the level 2 bounty (non-endless) shows the normal endless bounty rewards with the amber stars and whatnot and the level 3 (endless) shows those of the level 2 bounty.

Screenshots, evidence:
https://i.imgur.com/iJn178e.png

**Comment by TobiTenno** [comment]
Without the correlation between what tables were on the worldstate at the same time, I don't have a way to find out what caused this to appear swapped.

**Comment by TobiTenno** [comment]
i don't think we're gonna get there anytime son, so i'll close this for now. if we get any more data from DE, i'll do what i can.
