### ISSUE TITLE
Active ISO Vault bounty rewards incorrect

### ISSUE THREAD

**Issue by TheMrBooyah** [WFCD/warframe-worldstate-parser#243]
**Summary (short):**
The shown Vault Bounty rewards are the ones from the normal bounties.

---
**Description:**
The rewards that are shown for the ISO Vault bounties are the ones from the normal bounties with the corresponding tier.
The issue should be solvable by updating the regex and taking the correct reward table.

Difference between the two is the normal bounties use "TierXTableXRewards" while the ISO Vault ones use "VaultBountyTierXTableXRewards". 
Instead of or together with the regex the property "isVault" could also be used to determine the correct rewards table.

---
**If issue, Reproduction:**
Retrieve the data and compare the normal bounties with the ISO vault bounties rewards. They are the same while they are not in game.

---
**Evidence:**

**Comment by TobiTenno** [comment]
right now, I'm not aware of the difference in the bounty string between the `Arcana Isolation Vault`s and `Isolation Vault`s, which will probably cause further issues

**Comment by TheMrBooyah** [comment]
Currently there is no difference in the Arcana Isolation Vault and Isolation vaults. Besides the Arcana bounties are not inside the worldstate at this moment.

**Comment by TobiTenno** [comment]
well, hopefully that's a good thing for now, i guess

**Comment by TheMrBooyah** [comment]
For now you could go with only the normal ISO vault rewards (As they are the same as Arcana) and change it when DE changes it?

**Comment by TobiTenno** [comment]
assuming they change, yeah, that's my plan
