### ISSUE TITLE
/${platform}/cambionCycle .timeLeft Attribute

### ISSUE THREAD

**Issue by ChaonengTan** [WFCD/warframe-worldstate-parser#329]
**Summary (short):**
https://api.warframestat.us/pc/cambionCycle dosent have a .timeLeft attribute

---
**Description:**
Although the .timeLeft is the same on Cetus as it is on Cambion Drift, obtaining .timeLeft would require two API calls.
I thought it would be best if .timeLeft was built into /${platform}/cambionCycle

**Comment by TobiTenno** [comment]
best? definitely relative, but sure. I can do that.
