### ISSUE TITLE
Explicitly look up language (requires warframe-worldstate-data change)

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-worldstate-parser#36]
Idea:
* Allow the consumer to specify a language (eg. english, spanish, etc) to look up a string for

Implementation arch:
* Default to what is currently returned if there is no language provided in whatever release the consumer is dependent on, but if `data['${language}']` exists, use that instead.

**Comment by aliasfalse** [comment]
@nspacestd any thoughts?

**Comment by nspacestd** [comment]
We could add a 'language' parameter to the translation functions or maybe move them in a 'Translator' class and pass the language to its constructor

**Comment by aliasfalse** [comment]
i think either way would work great.

**Comment by aliasfalse** [comment]
i think passing it in the function would let us not need new Worldstate objects for each language.

**Comment by nspacestd** [comment]
Either works for me. Passing it to the function might be better here, yeah
