### ISSUE TITLE
Arbitration returns an empty map

### ISSUE THREAD

**Issue by SlayerOrnstein** [WFCD/warframe-worldstate-parser#419]
**Summary (short):**
Arbitration are showing up as an empty map instead of null.

---
**Description:**
Arbitration should be null when there is an arbitration instead it's an empty map.

---
**If issue, Reproduction:**
Using either the worldstate endpoint or arbitration endpoint you'll get an empty map instead of a null value.

**Comment by TobiTenno** [comment]
i'll take a look tonight hopefully, i'm thinking we just need to default, but i'm not sure.... my worry is i dunno when i ever had that specific part returning null...
