### ISSUE TITLE
cambionCycle endpoint's "active" key should be renamed to "state".

### ISSUE THREAD

**Issue by Neppkun** [WFCD/warframe-worldstate-parser#426]
### What would you like to see happen?

Cetus, Vallis, and Earth use the "state" key for day/night (cold/warm for vallis) cycles, but Cambion uses "active". It should be renamed to "state" as well, because calling it "active" has no real use other than keeping it the same as the game. Calling it "state" will make it easier for developers that use the API.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
If you'd like to propose the change, I'll review it and approve as needed.

**Comment by Neppkun** [comment]
> If you'd like to propose the change, I'll review it and approve as needed.

Do you mean to make a PR?

**Comment by TobiTenno** [comment]
> > If you'd like to propose the change, I'll review it and approve as needed.
> 
> Do you mean to make a PR?

Yup

**Comment by TobiTenno** [comment]
You'd need one in this repo and in WFCD/api-spec

**Comment by Neppkun** [comment]
Alright, thanks.

**Comment by Neppkun** [comment]
https://github.com/WFCD/warframe-worldstate-parser/pull/427
https://github.com/WFCD/api-spec/pull/35
@TobiTenno opened PRs and they "work on my machine:tm:"

**Comment by TobiTenno** [comment]
closed by #427
api change coming on https://github.com/WFCD/warframe-status

**Comment by TobiTenno** [comment]
all done
