### ISSUE TITLE
Duviri cycle

### ISSUE THREAD

**Issue by Sainan** [WFCD/warframe-worldstate-parser#451]
I've noticed Duviri likes to switch around the 0th minute of every hour, so just using the UNIX epoch like this should be fine:
```C++
int main() {
    const char* stages[] = {
        "Sorrow",
        "Fear",
        "Joy",
        "Anger",
        "Envy",
    };
    time_t cycle_delta = ::time(nullptr) % 36'000;
    time_t stage = cycle_delta / 7'200;
    time_t stage_delta = cycle_delta % 7'200;
    time_t until_next_stage = 7'200 - stage_delta;
    std::cout << stages[stage] << " spiral. " << stages[(stage + 1) % 5] << " in " << (until_next_stage / 60) << " minutes.\n";
}
```

**Comment by TobiTenno** [comment]
likes to switch "around" might be a bit too rough for me, but i'll put it in for you.

**Comment by Sainan** [comment]
Well, I noticed it only maybe being off by up to 60 seconds.
![image](https://github.com/WFCD/warframe-worldstate-parser/assets/63328889/109bf8e5-364a-4df6-ac03-21daab9ee56f)
I'm sure it's possible to offset `cycle_delta` by a few seconds to approach perfection.

**Comment by TobiTenno** [comment]
i honestly don't know c++ enough to properly translate this to js, so it'll take me a bit, but i think i get the jist of it all

**Comment by TobiTenno** [comment]
got it converted. could you see if you can run this in your terminal and see if it gives you the same results? (or in your browser, either should work)

```js
const stages = [
    "Sorrow",
    "Fear",
    "Joy",
    "Anger",
    "Envy",
];
const cycleDelta = Math.floor(Date.now() / 1000) % 3600;
const stage = Math.floor(cycleDelta / 720);
const stageDelta = cycleDelta % 720;
const untilNext = 720 - stageDelta;
console.log(`${stages[stage]} spiral. ${stages[(stage + 1) % stages.length]} in ${Math.floor(untilNext / 60)} minutes.`);
```

**Comment by TobiTenno** [comment]
also, feel free to contact me on discord and we can debug more together if it doesn't match

u/n: tobiah

**Comment by Sainan** [comment]
I'm not sure why you removed the leading 0 from all time values, but this should be the correct translation of the latest version:
```JS
const stages = [
    "Sorrow",
    "Fear",
    "Joy",
    "Anger",
    "Envy",
];
const cycleDelta = (Math.floor(Date.now() / 1000) - 52) % 36000;
const stage = Math.floor(cycleDelta / 7200);
const stageDelta = cycleDelta % 7200;
const untilNext = 7200 - stageDelta;
console.log(`${stages[stage]} spiral. ${stages[(stage + 1) % stages.length]} in ${Math.floor(untilNext / 60)} minutes.`);
```

**Comment by TobiTenno** [comment]
well, my first one that matched this produced weird numbers, this worked better... so i'll get that set up someway.
