### ISSUE TITLE
New field "EndlessXpChoices"

### ISSUE THREAD

**Issue by muji06** [WFCD/warframe-worldstate-parser#455]
**Summary (short):**

Worldstate includes a new field called "EndlessXpChoices" with data for current circuit reward rotations

---
**Description:**

Basically includes the current weekly rewards for The Circuit on Duviri. 
There are 2 categories inside:
- "EXC_NORMAL" : Circuit reward choices on normal mode.
- "EXC_HARD" : Circuit reward choices on steel path mode.

No data other than the names of the weapons/warframes included.

Example data from worldstate:
```json
"EndlessXpChoices": [
	{
		"Category": "EXC_NORMAL",
		"Choices": [
			"Nekros",
			"Valkyr",
			"Oberon"
		]
	},
	{
		"Category": "EXC_HARD",
		"Choices": [
			"Lex",
			"Magistar",
			"Boltor",
			"Bronco",
			"CeramicDagger"
		]
	}
],
``` 
---
**Mockups:**

**Comment by TobiTenno** [comment]
Oh, and it's not even the unique names... ripperoni... not gonna be able to localize like that very easily...
