### ISSUE TITLE
Add isPermanent field for nightwave challanges 

### ISSUE THREAD

**Issue by aldi-f** [WFCD/warframe-worldstate-parser#486]
**Summary (short):**

Add permanent field for nightwave challenges that have it.

---
**Description:**
With the new Nightwave season we now have another type of challenges: permanent weekly ones.
Was checking the worldstate today and I saw that they actually included it there: 
_(Sorry for the formatting, I just tried to clean it up and only show one example from the array)_
```json
{
	"SeasonInfo": {
	"Activation": {
		"$date": {
			"$numberLong": "1701284400000"
		}
	},
	"Expiry": {
		"$date": {
			"$numberLong": "1719187200000"
		}
	},
	"AffiliationTag": "RadioLegionIntermission9Syndicate",
	"Season": 11,
	"Phase": 0,
	"Params": "",
	"ActiveChallenges": [

		{
			"_id": {
				"$oid": "001200030000000000000032"
			},
			"Permanent": true,
			"Activation": {
				"$date": {
					"$numberLong": "1702252800000"
				}
			},
			"Expiry": {
				"$date": {
					"$numberLong": "1702857600000"
				}
			},
			"Challenge": "/Lotus/Types/Challenges/Seasons/Weekly/SeasonWeeklyPermanentCompleteMissions"
		},
	]
	}
}
``` 

---
**Mockups:**

**Comment by TobiTenno** [comment]
@aldi-f feel free to comment/approve #487

**Comment by muji06** [comment]
The field is not present on all challenges so wouldn't that give undefined in those cases?
Maybe switching to this instead

```javascript
this.isPermanent = data.Permanent || false;
```
