### ISSUE TITLE
Feature Request: Parse Prime Resurgance data

### ISSUE THREAD

**Issue by Foretack** [WFCD/warframe-worldstate-parser#525]
It would be nice to have an api endpoint to check previous prime resurgances and the expiry of current one.

The path for this data is on worldState.php $.PrimeVaultTraders[0].ScheduleInfo

**Comment by TobiTenno** [comment]
I can probably parse a good bit out :+1:

**Comment by TobiTenno** [comment]
looking at it, we do parse ScheduleInfo...

**Comment by Foretack** [comment]
oh? I don't seem to find what I'm looking for in https://docs.warframestat.us

**Comment by SlayerOrnstein** [comment]
> oh? I don't seem to find what I'm looking for in [docs.warframestat.us](https://docs.warframestat.us)

https://api.warframestat.us/pc/vaultTrader/

**Comment by Foretack** [comment]
> > oh? I don't seem to find what I'm looking for in [docs.warframestat.us](https://docs.warframestat.us)
> 
> [api.warframestat.us/pc/vaultTrader](https://api.warframestat.us/pc/vaultTrader/)

Thank you. Perhaps this should be added to the docs then ^^

**Comment by TobiTenno** [comment]
we added what we knew of at the time, we purposely pass through what we can... you can also add it to the docs yourself? i'll work on getting a ticket opened to document that part when i can, but this is also not something high priority, as it does exist

**Comment by Foretack** [comment]
> we added what we knew of at the time, we purposely pass through what we can... you can also add it to the docs yourself? i'll work on getting a ticket opened to document that part when i can, but this is also not something high priority, as it does exist

Opened a PR for it on the warframe-status repo 👍
