### ISSUE TITLE
Generated identifiers may erroneously change as `warframe-worldstate-parser` is updated

### ISSUE THREAD

**Issue by DaxterSpeed** [WFCD/warframe-worldstate-parser#66]
Various objects in the parser automatically generate an identifier where the official API doesn't provide any. These objects however rely on the names of items *after* they've either been normalized or mapped using data from `warframe-worldstate-data`. This in turn means that if `warframe-worldstate-data` updates the mapping of a string - or if the normalization process changes - the identifier will "erroneously" change. 

A FlashSale make for a great example:
```json
{
  "item": "Tn S M G Weapon", 
  "expiry": "2018-12-31T00:00:00.000Z", 
  "discount": 0, 
  "premiumOverride": 240, 
  "isFeatured": true, 
  "isPopular": false, 
  "id": "1546214400000Tn S M G Weapon", 
  "expired": false, 
  "eta": "352d 18h 29m 35s"
}, 
```

In this case when `/Lotus/Weapons/Tenno/LongGuns/TnSMG/TnSMGWeapon` is identified in `warframe-worldstate-data` this deal's `id` would change, even though no deals have been added, removed or changed.

I propose that all generated ids are changed to only use "reliable" information. For the example above a possible updated id could be: `1546214400000TnSMGWeapon`, using only the last segment of the original identifier string.

I'd be willing to help implement this if necessary.

**Comment by Tithen-Firion** [comment]
I think that's the point. Take Hub for example. There's new item and it's in featured deals. We update the names and Hub displays that item second time. Refresh site and it's gone but still. Also: spaces and anything beside letter as first character causes compatibility problems for HTML IDs. So I suggest last token from "name path" and then timestamp: `TnSMGWeapon1546214400000`.

**Comment by TobiTenno** [comment]
Feel free to submit a PR, it's not high priority for me at this time, but if you feel it necessary, we'll review it in PR

**Comment by TobiTenno** [comment]
#67 i did it anyway

**Comment by TobiTenno** [comment]
oh, this has been done for a while. let me know if there's any further <3
